#!/bin/bash

cd /opt/nexus

exec java \
    -server \
    $JAVA_ARGS \
    -XX:+UnlockDiagnosticVMOptions \
    -XX:MaxDirectMemorySize=2703m \
    -XX:+UnlockDiagnosticVMOptions \
    -XX:+LogVMOutput \
    -XX:LogFile=/dev/stdout \
    -XX:-OmitStackTraceInFastThrow \
    -Djava.net.preferIPv4Stack=true \
    -Dkaraf.home=. \
    -Dkaraf.base=. \
    -Dkaraf.etc=/opt/nexus/etc/karaf \
    -Djava.util.logging.config.file=etc/karaf/java.util.logging.properties \
    -Dkaraf.data=/opt/nexus/data \
    -Dkaraf.log=/opt/nexus/log \
    -Djava.io.tmpdir=/opt/nexus/tmp \
    -Dkaraf.startLocalConsole=false \
    -Djdk.tls.ephemeralDHKeySize=2048 \
    -Djava.endorsed.dirs=/opt/nexus/lib/endorsed \
    -classpath .:/opt/nexus/lib/boot/* org.sonatype.nexus.karaf.NexusMain